### PR TITLE
[cooperative perception] Add semantic class to message generation

### LINKED ISSUE #2232: [cooperative perception] CP stack does not propagate semantic class information
### Summary

The CP stack currently drops semantic class information when it ingests external objects. Downstream CARMA components, such as motion computation, need that information to predict motion using the appropriate model.

### Commit

`develop`

### Expected Behavior

CP stack propagates semantic class data

### Actual Behavior

CP stack drops semantic class data

### Steps to Reproduce the Actual Behavior

1. Inspect code

### Related Work

[CDAR-621](https://usdot-carma.atlassian.net/browse/CDAR-621)

[CDAR-621]: https://usdot-carma.atlassian.net/browse/CDAR-621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by adamlm**
# PR Details
## Description

This PR adds semantic class information to the CP stack. Downstream CARMA components, such as the motion computation node, relies on this information to choose the appropriate propagation model. Previously, the semantic class information was being droppped.

## Related GitHub Issue

Closes #2232 

## Related Jira Key

Closes [CDAR-621](https://usdot-carma.atlassian.net/browse/CDAR-621)

## How Has This Been Tested?

Manually in integration testing

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [x] All new and existing tests passed.

[CDAR-621]: https://usdot-carma.atlassian.net/browse/CDAR-621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: carma_cooperative_perception/src/msg_conversion.cpp [hunk 1]
```diff
@@ -322,19 +322,24 @@ auto to_detection_msg(
...
+        detection.semantic_class = detection.SEMANTIC_CLASS_MOTORCYCLE;
         break;
       case object.PEDESTRIAN:
         detection.motion_model = motion_model_mapping.pedestrian_model;
+        detection.semantic_class = detection.SEMANTIC_CLASS_PEDESTRIAN;
         break;
       case object.UNKNOWN:
       default:
         detection.motion_model = motion_model_mapping.unknown_model;
+        detection.semantic_class = detection.SEMANTIC_CLASS_UNKNOWN;
```
Comment (MishkaMN) [inline carma_cooperative_perception/src/msg_conversion.cpp:342]: 273-284 lines look similar as well, should we have it there?

**Review by MishkaMN — CHANGES_REQUESTED** [review]

File: carma_cooperative_perception/src/multiple_object_tracker_component.cpp [hunk 2]
```diff
@@ -155,6 +193,8 @@ static auto to_ros_msg(const mot::CtraTrack & track) noexcept
 
   msg.accel.accel.linear.x = mot::remove_units(track.state.acceleration);
 
+  msg.semantic_class = semantic_class_to_numeric_value(mot::get_semantic_class(track));
+
```
Comment (MishkaMN) [inline carma_cooperative_perception/src/multiple_object_tracker_component.cpp:197]: Looks like we need a function in the library? `get_semantic_class`

Comment (adamlm) [reply carma_cooperative_perception/src/multiple_object_tracker_component.cpp:197]: Yes. That function was introduced in a spike branch for `multiple_object_tracking`. We should merge those changes before merging this PR.

File: carma_cooperative_perception/src/msg_conversion.cpp (hunk 1 above)
Comment (adamlm) [reply carma_cooperative_perception/src/msg_conversion.cpp:347]: The semantic classes from SDSMs don't have a great mapping to our sematic classes, but we can do a "best-effort" conversion.

Comment (MishkaMN) [reply carma_cooperative_perception/src/msg_conversion.cpp:347]: The SDSM standard is using J2735 BasicVehicleClass msg (https://github.com/usdot-fhwa-stol/carma-msgs/blob/develop/j2735_msgs/msg/BasicVehicleClass.msg#L103). 
We decided to use the LIGHT_TRUCK_VEHICLE_TYPE_UNKNOWN=20 for the large trucks VRU use case using. So once we support that conversion and message type, we can include that option here. I created an issue:

Comment (MishkaMN) [reply carma_cooperative_perception/src/msg_conversion.cpp:347]: https://github.com/usdot-fhwa-stol/carma-platform/issues/2240

**Comment by MishkaMN** [comment]
Made a mistake in merging this too soon before merging https://github.com/usdot-fhwa-stol/multiple_object_tracking/pull/121, which this PR depends on.
