### PR TITLE
Switch twist source for Detections

### LINKED ISSUE #2218: [cooperative perception] External object to detection conversion uses wrong twist fields
### Summary

The `to_detection_msg` function uses the `velocity_inst`, which does not get fully populated by upstream components. It should use the `velocity` field instead.

### Commit

`develop`

### Expected Behavior

The `to_detection_msg` function populates `Detection` messages' `twist` fields with data from `velocity`.

### Actual Behavior

The `to_detection_msg` function populates `Detection` messages' `twist` fields with data from `velocity_inst`.

### Steps to Reproduce the Actual Behavior

1. Inspect code

### Related Work

[CDAR-608](https://usdot-carma.atlassian.net/browse/CDAR-608)

[CDAR-608]: https://usdot-carma.atlassian.net/browse/CDAR-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by adamlm**
# PR Details
## Description

This PR resolves a bug when converting external object data to detection data in the cooperative perception stack. The external object to detection conversion function was using velocity_inst instead of velocity. The former has twist values but not the corresponding covariance matrixes.

## Related GitHub Issue

Closes #2218 

## Related Jira Key

Closes [CDAR-608](https://usdot-carma.atlassian.net/browse/CDAR-608)

## Motivation and Context

The missing covariance matrices was causing issues for downstream cooperative perception stack components.

## How Has This Been Tested?

Manually in integration testing

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [x] All new and existing tests passed.

[CDAR-608]: https://usdot-carma.atlassian.net/browse/CDAR-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MishkaMN — APPROVED** [review]

File: carma_cooperative_perception/src/msg_conversion.cpp [hunk 1]
```diff
@@ -314,8 +314,8 @@ auto to_detection_msg(
     detection.pose = object.pose;
   }
 
-  if (object.presence_vector & object.VELOCITY_INST_PRESENCE_VECTOR) {
-    detection.twist = object.velocity_inst;
+  if (object.presence_vector & object.VELOCITY_PRESENCE_VECTOR) {
+    detection.twist = object.velocity;
```
Comment (MishkaMN) [inline carma_cooperative_perception/src/msg_conversion.cpp:318]: There seems to be several more instances of velocity_inst being used in this file and its corresponding test file. Do we not need those changed?

**Review by MishkaMN — CHANGES_REQUESTED** [review]

File: carma_cooperative_perception/src/msg_conversion.cpp (hunk 1 above)
Comment (adamlm) [reply carma_cooperative_perception/src/msg_conversion.cpp:318]: Yes. Good catch.

**Review by MishkaMN — APPROVED** [review]
