### PR TITLE
Install multiple object tracking deps

### LINKED ISSUE #2267: CARMA Platform Docker build CI is broken
### Summary

The Docker build process for CARMA Platform environment does not install dependencies needed for the multiple object tracking library.

### Commit

`develop`

### Expected Behavior

Docker build CI process for CARMA Platform completes successfully

### Actual Behavior

Docker build CI process for CARMA Platform fails due to missing dependencies

### Steps to Reproduce the Actual Behavior

1. Run Docker build CI pipeline

### Related Work

[CDAR-712](https://usdot-carma.atlassian.net/browse/CDAR-712)

[CDAR-712]: https://usdot-carma.atlassian.net/browse/CDAR-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by adamlm**
# PR Details
## Description

The multiple object tracking library no longer installs its own dependencies, so we must install them manually. The `docker/install.sh` script now calls the library's `install_dependencies.sh` script.

## Related GitHub Issue

Closes #2267 

## Related Jira Key

Closes [CDAR-712](https://usdot-carma.atlassian.net/browse/CDAR-712)

## Motivation and Context

Resolve Docker build failure

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.

[CDAR-712]: https://usdot-carma.atlassian.net/browse/CDAR-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: docker/install.sh [hunk 1]
```diff
@@ -33,6 +33,9 @@ fi
 
 cd ~/carma_ws
 
+echo "Installing multiple object tracking dependencies"
+sudo ./src/multiple_object_tracking/scripts/install_dependencies.sh
```
Comment (JonSmet) [inline docker/install.sh:37]: It looks like CI using the CircleCI config is currently failing. Could you add a step for this in `.circleci/config.yml`? Looks like we could add the step after the `docker/checkout.bash` script is called [here](https://github.com/usdot-fhwa-stol/carma-platform/blob/d173d2db1be0748e2e6593a41351cdd2236d7823/.circleci/config.yml#L59).

File: docker/install.sh [hunk 2]
```diff
@@ -1,13 +1,13 @@
 #!/bin/bash
 
 #  Copyright (C) 2018-2023 LEIDOS.
-#
```
Comment (JonSmet) [inline docker/install.sh:4]: Not actually a comment on the `docker/install.sh` file changes, but can you update the PR description to indicate that the `docker/install.sh` file was updated rather than `docker/checkout.bash`?

**Review by JonSmet — CHANGES_REQUESTED** [review]

File: docker/install.sh (hunk 2 above)
Comment (adamlm) [reply docker/install.sh:4]: Done

**Review by JonSmet — APPROVED** [review]
